<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Appium-Framework" duration-ms="427" started-at="2015-04-10T10:06:39Z" finished-at="2015-04-10T10:06:39Z">
    <groups>
      <group name="sanity">
        <method signature="InvalidLoginTest.verifyInvalidLoginTest()[pri:0, instance:IntegrationTests.tests.InvalidLoginTest@6fadae5d]" name="verifyInvalidLoginTest" class="IntegrationTests.tests.InvalidLoginTest"/>
        <method signature="LoginTest.verifyLoginLogoutTest()[pri:0, instance:IntegrationTests.tests.LoginTest@6cd8737]" name="verifyLoginLogoutTest" class="IntegrationTests.tests.LoginTest"/>
        <method signature="SavedConnectionsTest.verifySavedConnectionsFeatures()[pri:0, instance:IntegrationTests.tests.SavedConnectionsTest@566776ad]" name="verifySavedConnectionsFeatures" class="IntegrationTests.tests.SavedConnectionsTest"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Mobikwik Automation Tests" duration-ms="427" started-at="2015-04-10T10:06:39Z" finished-at="2015-04-10T10:06:39Z">
      <class name="IntegrationTests.tests.SavedConnectionsTest">
        <test-method status="FAIL" signature="teardown()[pri:0, instance:IntegrationTests.tests.SavedConnectionsTest@566776ad]" name="teardown" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at IntegrationTests.lib.CreateSession.teardown(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="SKIP" signature="verifySavedConnectionsFeatures()[pri:0, instance:IntegrationTests.tests.SavedConnectionsTest@566776ad]" name="verifySavedConnectionsFeatures" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySavedConnectionsFeatures -->
        <test-method status="SKIP" signature="instantiateHelpers(java.lang.String)[pri:0, instance:IntegrationTests.tests.SavedConnectionsTest@566776ad]" name="instantiateHelpers" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- instantiateHelpers -->
        <test-method status="SKIP" signature="createDriver(java.lang.String)[pri:0, instance:IntegrationTests.tests.SavedConnectionsTest@566776ad]" name="createDriver" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriver -->
      </class> <!-- IntegrationTests.tests.SavedConnectionsTest -->
      <class name="IntegrationTests.tests.InvalidLoginTest">
        <test-method status="PASS" signature="invokeAppium()[pri:0, instance:IntegrationTests.tests.InvalidLoginTest@6fadae5d]" name="invokeAppium" is-config="true" duration-ms="5094" started-at="2015-04-10T15:36:34Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invokeAppium -->
        <test-method status="FAIL" signature="createDriver(java.lang.String)[pri:0, instance:IntegrationTests.tests.InvalidLoginTest@6fadae5d]" name="createDriver" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[android]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[ERROR running Appium command: write EPIPE
Command duration or timeout: 114 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:58'
System info: host: 'Sanjit-pc', ip: '192.168.56.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_40'
Driver info: io.appium.java_client.android.AndroidDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: ERROR running Appium command: write EPIPE
Command duration or timeout: 114 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:58'
System info: host: 'Sanjit-pc', ip: '192.168.56.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_40'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:109)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:39)
	at IntegrationTests.lib.CreateSession.androidDriver(Unknown Source)
	at IntegrationTests.lib.CreateSession.createDriver(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriver -->
        <test-method status="SKIP" signature="instantiateHelpers(java.lang.String)[pri:0, instance:IntegrationTests.tests.InvalidLoginTest@6fadae5d]" name="instantiateHelpers" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- instantiateHelpers -->
        <test-method status="SKIP" signature="verifyInvalidLoginTest()[pri:0, instance:IntegrationTests.tests.InvalidLoginTest@6fadae5d]" name="verifyInvalidLoginTest" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidLoginTest -->
        <test-method status="FAIL" signature="teardown()[pri:0, instance:IntegrationTests.tests.InvalidLoginTest@6fadae5d]" name="teardown" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at IntegrationTests.lib.CreateSession.teardown(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="SKIP" signature="stopAppium()[pri:0, instance:IntegrationTests.tests.InvalidLoginTest@6fadae5d]" name="stopAppium" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopAppium -->
      </class> <!-- IntegrationTests.tests.InvalidLoginTest -->
      <class name="IntegrationTests.tests.LoginTest">
        <test-method status="SKIP" signature="createDriver(java.lang.String)[pri:0, instance:IntegrationTests.tests.LoginTest@6cd8737]" name="createDriver" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriver -->
        <test-method status="SKIP" signature="instantiateHelpers(java.lang.String)[pri:0, instance:IntegrationTests.tests.LoginTest@6cd8737]" name="instantiateHelpers" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- instantiateHelpers -->
        <test-method status="FAIL" signature="teardown()[pri:0, instance:IntegrationTests.tests.LoginTest@6cd8737]" name="teardown" is-config="true" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at IntegrationTests.lib.CreateSession.teardown(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="SKIP" signature="verifyLoginLogoutTest()[pri:0, instance:IntegrationTests.tests.LoginTest@6cd8737]" name="verifyLoginLogoutTest" duration-ms="0" started-at="2015-04-10T15:36:39Z" finished-at="2015-04-10T15:36:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginLogoutTest -->
      </class> <!-- IntegrationTests.tests.LoginTest -->
    </test> <!-- Mobikwik Automation Tests -->
  </suite> <!-- Appium-Framework -->
</testng-results>
